SELECT AA.LOC, ROUND(SUM(NVL(COMM,0)),0) AS HAP
FROM (
    SELECT ENAME, SAL, COMM, DNAME, LOC
    FROM EMP EM JOIN DEPT DE
    ON EM.DEPTNO = DE.DEPTNO
) AA
GROUP BY AA.LOC HAVING ROUND(SUM(NVL(COMM,0)),0) <= 20 ORDER BY AA.LOC DESC;


CREATE TABLE EMP(
    EMPNO       NUMBER(4)  PRIMARY KEY,
    ENAME       VARCHAR2(10),
    JOB            VARCHAR2(9),
    MGR            NUMBER(4),
    HIREDATE  DATE,
    SAL            NUMBER(7,2),
    COMM        NUMBER(7,2),
    DEPTNO    NUMBER(7) REFERENCES DEPT(DEPTNO));
    
    SELECT * FROM DEPT;
    
    INSERT INTO EMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, DEPTNO)
    VALUES (7698, ' BACK', 'HEAD', 7698,'2000-07-12', 325, 20);
    
    INSERT INTO EMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, DEPTNO)
    VALUES (7690, ' KIM', 'EMPLOYEE', 7698,'2000-06-12', 322, 10);
    
    INSERT INTO EMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, DEPTNO)
    VALUES (75521, ' BEE', 'EMPLOYEE', 7698,'2000-07-12', 325, 20);
    
    INSERT INTO EMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, DEPTNO)
    VALUES (7642, ' TEA', 'EMPLOYEE', 7698,'2000-07-12', 325, 20);
    
    INSERT INTO EMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, DEPTNO)
    VALUES (7111, ' SOO', 'INTERN', 7690,'2000-07-12', 325, 20);
    
    INSERT INTO EMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, DEPTNO)
    VALUES (1212, ' BIN', 'INTERN', 7641,'2000-07-12', 325, 20);
    
    INSERT INTO EMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, DEPTNO)
    VALUES (8918, ' TIN', 'INTERN', 7641,'2000-07-12', 325, 20);
    
    
    SELECT * FROM EMP;
    
    SELECT * 
    FROM EMP JOIN DEPT
    ON EMP.DEPTNO = DEPT.DEPTNO;
    
    SELECT * FROM EMP, DEPT
    WHERE EMP.DEPTNO = DEPT.DEPTNO;
    
    SELECT EMP.EMPNO, EMP.ENAME, DEPT.DEPTNO, DEPT.DNAME
    FROM EMP JOIN DEPT
    ON EMP.DEPTNO = DEPT.DEPTNO;
    
    SELECT * FROM DEPT;
    
    
    